# fly.toml app configuration file generated for delicate-leaf-1250 on 2023-05-29T08:57:27-10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "delicate-leaf-1250"
primary_region = "lax"

[env]
  PORT = "8080" # add this

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
